CREATE SEQUENCE IF NOT EXISTS HOTELIER_SEQUENCE START WITH 100 BELONGS_TO_TABLE;
CREATE SEQUENCE IF NOT EXISTS ITEM_SEQUENCE START WITH 100 BELONGS_TO_TABLE;
CREATE SEQUENCE IF NOT EXISTS LOCATION_SEQUENCE START WITH 100 BELONGS_TO_TABLE;

CREATE TABLE IF NOT EXISTS HOTELIER(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "HOTELIER_SEQUENCE" NOT NULL NULL_TO_DEFAULT SEQUENCE "HOTELIER_SEQUENCE",
    "FIRST_NAME" VARCHAR(255),
    "LAST_NAME" VARCHAR(255),
    PRIMARY KEY("ID")
);

CREATE TABLE IF NOT EXISTS ITEM(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "ITEM_SEQUENCE" NOT NULL NULL_TO_DEFAULT SEQUENCE "ITEM_SEQUENCE",
    "NAME" VARCHAR(255),
    "RATING" INTEGER,
    "CATEGORY" TINYINT,
    "IMAGE" VARCHAR(255),
    "REPUTATION" INTEGER,
    "REPUTATION_BADGE" TINYINT,
    "PRICE" BIGINT,
    "AVAILABILITY" INTEGER,
    "LOCATION_ID" BIGINT,
    "HOTELIER_ID" BIGINT,
    PRIMARY KEY("ID")
);

CREATE TABLE IF NOT EXISTS LOCATION(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "LOCATION_SEQUENCE" NOT NULL NULL_TO_DEFAULT SEQUENCE "LOCATION_SEQUENCE",
    "CITY" VARCHAR(255),
    "STATE" VARCHAR(255),
    "COUNTRY" VARCHAR(255),
    "ZIP_CODE" INTEGER,
    "ADDRESS" VARCHAR(255),
    PRIMARY KEY("ID")
);

ALTER TABLE ITEM ADD FOREIGN KEY (HOTELIER_ID) REFERENCES HOTELIER (ID) NOCHECK;

ALTER TABLE ITEM ADD FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION (ID) NOCHECK;
