CREATE SEQUENCE IF NOT EXISTS HOTELIER_SEQUENCE START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE IF NOT EXISTS ITEM_SEQUENCE START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE IF NOT EXISTS LOCATION_SEQUENCE START WITH 1 BELONGS_TO_TABLE;

CREATE TABLE IF NOT EXISTS HOTELIER(
    "HOTELIER_ID" BIGINT DEFAULT NEXT VALUE FOR "HOTELIER_SEQUENCE" NOT NULL NULL_TO_DEFAULT SEQUENCE "HOTELIER_SEQUENCE",
    "FIRST_NAME" VARCHAR(255),
    "LAST_NAME" VARCHAR(255),
    PRIMARY KEY("HOTELIER_ID")
);

CREATE TABLE IF NOT EXISTS ITEM(
    "ITEM_ID" BIGINT DEFAULT NEXT VALUE FOR "ITEM_SEQUENCE" NOT NULL NULL_TO_DEFAULT SEQUENCE "ITEM_SEQUENCE",
    "NAME" VARCHAR(255),
    "RATING" INTEGER,
    "CATEGORY" VARCHAR(255),
    "IMAGE" VARCHAR(255),
    "REPUTATION" INTEGER,
    "REPUTATION_BADGE" VARCHAR(255),
    "PRICE" BIGINT,
    "AVAILABILITY" INTEGER,
    "LOCATION_LOCATION_ID" VARCHAR(255),
    "HOTELIER_HOTELIER_ID" VARCHAR(255),
    PRIMARY KEY("ITEM_ID")
);

ALTER TABLE ITEM ADD FOREIGN KEY (LOCATION_LOCATION_ID) REFERENCES LOCATION (LOCATION_ID) NOCHECK;

ALTER TABLE ITEM ADD FOREIGN KEY (HOTELIER_HOTELIER_ID) REFERENCES USER (HOTELIER_ID) NOCHECK;

CREATE TABLE IF NOT EXISTS LOCATION(
    "LOCATION_ID" INTEGER,
    "CITY" VARCHAR(255),
    "STATE" VARCHAR(255),
    "COUNTRY" VARCHAR(255),
    "ZIP_CODE" INTEGER,
    "ADDRESS" VARCHAR(255),
    PRIMARY KEY("LOCATION_ID")
);
